### ISSUE TITLE
[BUG] Command-line args cause app to crash

### ISSUE THREAD

**Issue by moritzschuell** [Apodini/Apodini#137]
**Describe the bug**
Previously one could provide command-line arguments to the app.
E.g. for the certificate used by the `HTTP2Configuration`: `--cert="/some/path/cert.pem"`.

When doing this on the current `develop`, this results in:
```
Fatal error: Error raised at top level: .unknownCommand("--cert=/some/path/cert.pem", available: ["boot", "serve", "routes"]): file Swift/ErrorType.swift, line 200
```

I think this changed behavior was introduced with the decoupling of `Vapor.Application`.

**To Reproduce**
Start the app with an additional command-line argument, e.g. `--cert="/some/path/cert.pem"`.

**Expected behavior**
Custom command-line arguments should be forwarded, as previously.

**Possible solution**
As of now, I think only the `HTTP2Configuration` is actually offering the possibility to use command-line arguments to configure it (with certificates in this case).
So I see two possibilities:
- Remove the possibility to use command-line args from `HTTP2Configuration`, since it also offers the possibility to configure the certificates in code. However, this would make it necessary to recompile the server each time the user might want to change certifcate 🙁
- Restore previous behavior by adding command-line arg support to our `Apodini.Application`.

**Comment by moritzschuell** [comment]
@tgymnich What's your take on that? I guess simply removing support for command-line arguments in `HTTP2Configuration` is the most pragmatic solution.

**Comment by PSchmiedmayer** [comment]
@moritzschuell Good catch! I would suggest to do the following:
We should make sure that a Vapor Application instance doesn't depend on command line arguments. I think this is a consequential next step from removing Vapor form the public interface. This is why I had [these manually defined arguments in the WebService creation](https://github.com/Apodini/Apodini/blob/7e036561efd185c9433d6889aec9efd6552ef007/Sources/Apodini/WebService.swift#L39-L45):
```swift
#if DEBUG
let arguments = [CommandLine.arguments.first ?? ".", "serve", "--env", "development", "--hostname", "0.0.0.0", "--port", "8080"]
#else
let arguments = [CommandLine.arguments.first ?? ".", "serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
#endif

var env = try Vapor.Environment.detect(arguments: arguments)
```

 I have missed that they have been removed by #82. I would suggest to add them again. 

 In addition I would suggest to use the Swift [ArgumentParser](https://github.com/apple/swift-argument-parser) to parse the arguments in `HTTP2Configuration`.

**Comment by lukaskollmer** [comment]
I'm running into the same issue trying to start a web service with custom arguments.
We definitely need to support some kind of CLI argument passing, instead of hard-coding things into the executable.

@PSchmiedmayer I'm not sure if the swift argument parser is the best idea here, since different parts of Apodini might expect their own command line arguments, and iirc the argument parser will fail if there's unexpected arguments (for example, the HTTP2Configuration uses `--cert`, whereas i would need to add things like `--export-path`. If the HTTP2Configuration defines an argument-parser-conformant struct for getting its cert argument, but my export path is also specified that would cause an error.)

Another kinda related issue I've run into in the past is that Vapor, if its environment object was created from CLI arguments containing the `--port` option, will not allow you to change the port by reassigning `app.http.server.configuration.port`. I didn't really investigate this back then (removing the port option from the args array fixed the issue), but that might cause trouble with some of our custom configuration APIs, if the user wants to manually specify a custom hostname/port.

**Comment by tgymnich** [comment]
@moritzschuell I will try to see what it takes to bring this feature back. Its a feature worth having in Apodini.
@lukaskollmer maybe (I haven't looked into it) Vapors [ConsoleKit](https://github.com/vapor/console-kit) would be more suitable than ArgumentParser.
