### ISSUE TITLE
[MINOR FEATURE] Allow handle() to return Void

### ISSUE THREAD

**Issue by hendesi** [Apodini/Apodini#177]
**Is your feature request related to a problem? Please describe.**
As found in [thread](https://github.com/Apodini/Apodini/pull/70/files/00759a1d3bf1f57b10ed377218010dd67d9848e0#r559817626), there is currently no possibility to return an `EventloopFuture<Void>` from a `handle()` function. This is due to `Void` being unable to conform to `ResponseTransformable`. Adding the conformance or a workaround would be beneficial for handlers that offer functionality which does not need to return something (e.g. `Delete` handler in the database target) 

**Propose a solution**
We could think of transforming `Void` to `.final(Void())` to be able to return it as a `Response`. Another option for the handlers, not really recommended though, would be to return `.nothing`. This is not really recommended as this does not create any response at all to the client which can be misleading. 

3. Option: Define a struct that conforms to `Encodable` and use/return it as a type alias for `Void`. This would allow us to have a clear and unified way, we and developers can use to indicate that a response is empty.

**Comment by nerdsupremacist** [comment]
We need to think about how void would be represented in GraphQL, since GraphQL requires that every field returns a value. So void doesn't really exist. Perhaps we can represent it as an enum with a single case?

**Comment by hendesi** [comment]
@PSchmiedmayer @Supereg 
Over the weekend I experimented a lot with refactoring the `Response` in order to support void. Also with looking at the [refactoring](https://gist.github.com/PSchmiedmayer/b26e268f3eee5092d6cb419abf68de98) proposed by Paul. 
While refactoring of `Response` was quite doable, I seem to get stuck on `ResponseTransformable`. If we want to be able to return `EventloopFuture<Void>` from handle(), we need to move away from constraining `ResponseTransformable.Content` to `Encodable`. As the internal structure relies heavily on expecting a encodable type, this would mean to refactor basically every exporter and context to manually check if content is conforming to encodable. This would still mean that at some point we lose the `Void` type and convert into something encodable. 

Although I spent quite a few hours on this...if you have any comments or tip or I missed something there completely, please let met know :D 

Since for now the only real use case that would profit from this refactoring is the `Delete` handler and there is not much time left in this project, I would propose this solution (similar to 3. option above): 
```
public struct NoContent: Encodable {
    var status: HTTPResponseStatus
    
    public init(_ status: HTTPResponseStatus) {
        self.status = status
    }
    
    public static var ok: NoContent {
        NoContent(.ok)
    }
}
```
This would allow us to have a clear way the user can use, if he doesn't want to have anything returned and since it is encodable there is no need to change the internal structure of Apodini.

**Comment by PSchmiedmayer** [comment]
@hendesi Thanks for reaching out. 

I agree with your opinion that it is not desirable to move `ResponseTransformable` away from constraining `ResponseTransformable.Content` to `Encodable`. I agree that this would overcomplicate the implementation for the different exporters.

As shared last time I would suggest to have a `Response` type like this:
```swift
enum Status {
    case ok
    case noContent
}

enum ConnectionEffect {
    case open
    case close
}

struct Response<Element> {
    struct Empty: Encodable {}
    
    private let _element: Element?
    let connectionEffect: ConnectionEffect
    let status: Status?
    
    var encodable: Encodable? {
        guard let _element = _element else {
            return nil
        }
        
        if _element is Void {
            return Empty()
        }
        
        guard let _encodable = _element as? Encodable else {
            fatalError("A non-nil input of a `Reponse` must conform to `Encodable`")
        }
        
        return _encodable
    }
    
    private init(_ element: Element?, connectionEffect: ConnectionEffect, status: Status? = nil) {
        if let element = element {
            precondition(element is Encodable || Element.self == Void.self, "The non-nil input of a `Reponse` that is not `Void` must conform to `Encodable`")
        }
        
        self.connectionEffect = connectionEffect
        self._element = element
        self.status = status
    }
    
    static var nothing: Response<Void> {
        Response<Void>(nil, connectionEffect: .open)
    }
    
    static var end: Response<Void> {
        Response<Void>(nil, connectionEffect: .close)
    }
    
    static func send<E: Encodable>(_ element: E, status: Status? = nil) -> Response<E> {
        Response<E>(element, connectionEffect: .open, status: status)
    }
    
    static func send(_ status: Status? = nil) -> Response<Void> {
        Response<Void>(Void(), connectionEffect: .open, status: status)
    }
    
    static func final<E: Encodable>(_ element: E, status: Status? = nil) -> Response<E> {
        Response<E>(element, connectionEffect: .close, status: status)
    }
    
    static func final(_ status: Status? = nil) -> Response<Void> {
        Response<Void>(Void(), connectionEffect: .close, status: status)
    }
}
```
Compared to the `NoContent` type which would require the exporters to check for this "magic" type the generalized `Response` type would allow a more generic handling to e.g. also adapt the status for responses that do respond with a non empty response. E.g. the `Create` `Handler` would return the created instance and a `creates` `Status` that would map to a `201` status code for a RESTful exporter. 

While it will not be easily possible to make `EventLoopFuture<Void>` conform to `ResponseTransformable` it should be easy to add an extension to `EventLoopFuture<Void>` that implements something similar to this:
```swift
extension EventLoopFuture where Value == Void {
    func transformToResponse(withStatus status: Status? = nil) -> EventLoopFuture<_Response<Void>> {
        map {
            _Response<Void>.final(status)
        }
    }
}
```

This could then be easily used in the `Delete` `Handler` that would pass in a suitable status. The same could apply for any other `Handler` that would normally return a `EventLoopFuture<Void>` and this would make it very easy to modify the status code if this would make sense for the `Handler`.
An example:
```swift
public struct Delete<Model: DatabaseModel>: Handler {
    @Apodini.Environment(\.database)
    private var database: Fluent.Database

    @Parameter(.http(.path))
    var id: Model.IDValue
    
    public func handle() -> EventLoopFuture<Response<Void>> {
        Model.find(id, on: database)
            .unwrap(orError: Abort(.notFound) )
            .flatMap { $0.delete(on: database ) }
            .transformToResponse(withStatus: .noContent)
    }
    
    public init() {}
}
```


Using the `Response` type the implementation of the `map`, `typeErasured` and `typed` should also be easier and the amount of switches made on the exporter level should also be reduced. Exporters can simply check of the presence of an `encodable` instance and due to the fact that `Response` only has an private initializer the assumptions that the type conforms to `Encodable` are always met. 

Regarding the `Response` type: I could imagine that we even automatically provide an `ok` status code if `encodable` is non nil or `noContent` if the `encodable` is nil:
```swift
struct Response<Element> {
    // ...
    
    private let _status: Status?
    
    // ...
    
    var status: Status {
        if let status = _status {
            return status
        }
        
        if encodable == nil {
            return .noContent
        } else {
            return .ok
        }
    }
    
    private init(_ element: Element?, connectionEffect: ConnectionEffect, status: Status? = nil) {
        // ...
        
        self._status = status
    }
    
    // ...
}
```
What do you think about this approach? This would make this even smarter than the example mentioned above and the exporters would need to do even less logic on their side.

I think that it should be possible to implement the `Response` type like this. On the other hand I can see that it is close to the end of the semester. Feel free to let me know if you think that you will be able to implement this until the final presentation or if it gets too close to the final deadline for you. We can discuss this in the team meeting tomorrow.
If this is not possible I can also implement this improvement after the final presentation based on the documentation provided this issue.

**Comment by hendesi** [comment]
@PSchmiedmayer 
Thanks for the detailed Response! There are actually some aspects in it, which I didn't see 👍 
I have some thoughts on this as well, especially on the conformance to `ReponseTransformable`, so it would be really cool to discuss this further in the work meeting.
