### ISSUE TITLE
[QUESTION] Do we have a defined strategy how to determine if a parameter is optional?

### ISSUE THREAD

**Issue by theMomax** [Apodini/Apodini#80]
### The Question

Do we have a defined strategy how to determine if a parameter is optional? What is this strategy?

### Background

I came across this question when I tried to use an `@Parameter` with an optional value with my own WebSocket exporter. The `@Parameter` internally stores an optional of `Element`. If this value is `nil` when the `@Parameter`'s `wrappedValue` is accessed, this results in a `fatalError`. The `@Parameter` does not check if `Element` is `ExpressibleByNilLiteral`. In that case `nil` would still be a valid option.

Basically the exporter currently decides if the `@Parameter`'s `element` is

* an `Optional<Element>(Optional<SomeType>(nil))` (which results in no fatal error)
* or an `Optional<Element>(nil)` (which results in fatal error)

when the request does not provide a value for an `@Parameter<Element> where Element: ExpressibleByNilLiteral`.

### Possible Solutions

All exporters have to use the same strategy. I currently see four strategies:

#### A: Optionality is declared by usage of `Optional`
```swift
// optional
@Parameter var firstName: String?
// required
@Parameter var surname: String
```
Pros: 
* feels natural

Cons:
* programmer cannot have a required parameter that can be `null`

#### B: Optionality is declared by Option
 ```swift
// optional
@Parameter(.necessity(.optional)) var firstName: String?
// required (default)
@Parameter var surname: String
```
Pros:
* programmer can have a required parameter that can be `null` (and is expressed as an `Optional` in code)

Cons:
* feels less natural
* more to write
* access to `wrappedValue` of `@Parameter` where `Element` is **not** `ExpressibleByNilLiteral` still results in fatal error

#### C: Optionality changes default Option
 ```swift
// optional (can be set to null explicitly)
@Parameter var firstName: String?
// required (cannot be set to null at all)
@Parameter var surname: String
// optional (cannot be set to null explicitly, invalid access results in fatal error)
@Parameter(.necessity(.optional)) var firstName2: String
// required (must be set to null explicitly)
@Parameter(.necessity(.required)) var surname2: String?
```
Pros:
* first two options feel natural
* programmer can have a required parameter that can be `null`

Cons:
* third variation can still result in fatal error
* more complicated to handle internally

#### D: Optionality is declared by usage of `Optional` with override
 ```swift
// optional (can be set to null explicitly)
@Parameter var firstName: String?
// required (cannot be set to null at all)
@Parameter var surname: String
// required (must be set to null explicitly)
@Parameter(.required) var surname2: String?
```
Pros:
* first two options feel natural
* programmer can have a required parameter that can be `null`

Cons:
* also complicated to handle internally

### Voting

In case there is no fixed strategy yet: please vote for one of following options: A (🎉), B (😄), C (👀), D (🚀)

Of course you can also comment on **why** you prefer a specific strategy or dislike another!

**Comment by bauer-andreas** [comment]
> The @Parameter does not check if Element is ExpressibleByNilLiteral.

Maybe some back story, because I think it fits also in this discussion. I think we didn't quite solve decoding optional Parameters (like `@Parameter var value: String?`).
In the case where `Element` is an optional, the `wrappedValue` is a "double" optional. Meaning if the "outer" optional does not hold a value, then there was no value injected/decoded (=> fatalError). Otherwise if a value was not encoded, the exporter would need to inject an Optional holding an empty Optional.
The problem is the current parameter retrieval, as I doesn't handle optional `Element`s. Is kind a messed up, imo.
I'm working on this, but I really have a hard time handling the case where `Element` is actually an optional. Because I can't access the `Wrapped` generic type of the `Optional<>` (at least not in such a generic way as e.g. the Vapor decode method expects it).

EDIT: I may have found a way kind a tacky way to get to the Wrapped Type. Not saying it will be clean code, but could work.

---

I think the goal for **now** would be Option A.

I get where you coming from. But I think being able to make a required Parameter with Type `Optional<SomeType>` is very specific to the WebSocket Exporter and the fact, that the WebSocket Exporter is currently using JSON, which makes a distinction between `null` and `undefined` (I could maybe see a similar use case in REST when defining multiple .content Parameters).
As it's a very niche use case I would go for a way of manually specifying `.required`, either using an exporter specific option or some generic way as you proposed it. I would decide that depending on how easy it is for the other exporters like (GraphQL or gRPC). Like, for GraphQL it works to just ignore WebSocket specific options, but would be harder to handle required `nil` (could be that GraphQL has `nil`, which I don't know, then this would probably be a bad example 😅).

**Comment by theMomax** [comment]
Thanks @Supereg for the quick response. I already had to solve the same problem in the WebSocketInfrastructure. I wrote a generic function (I would consider clean) that shifts the nil value to the inner optional, i.e. .none becomes .some(.none). You can find the code here: https://github.com/Apodini/Apodini/blob/422b12e9ba8ed65fc3b18ede29428468a30f0168/Sources/WebSocketInfrastructure/Input.swift#L218
This should be also applicable to Parameter.wrappedValue.

**Comment by bauer-andreas** [comment]
Thanks for sharing the code. So assuming `T` is `Optional<String>` (So `T?` is of type Optional<Optional<String>> right?).
If `value` holds a value, it will basically just return the same thing.
When `value` is passed as `Optional<Optional<String>>.none` it will basically just ship the `none` value into the inner Optional right?

I don't think this helps me at all. My fundamental problem is that I need to access the Wrapped Type if `T` is an Optional (In the above case I would need to access the `String` type), as I need to pass that Wrapped type onto e.g. Vapor for decoding e.g Query Parameters, Body or Path Parameters. And I assume other exporters have the same problem.
I'm at a point where I can access that Wrapped Type and pass it onto the Exporters retrieval method. I currently only need to rework how the value is returned and stored properly in the Parameter. EDIT: works.

**Comment by theMomax** [comment]
You are correct about what the code does. Seems like I misunderstood the problem you are encountering, but I got you now😄. I‘m glad you found a solution👍.

**Comment by bauer-andreas** [comment]
Some updates from my side. Writing some test currently, and encountered the following.

For parameters defined as:
```swift
@Parameter var name: String? = "Test"
```

This defines an optional parameter with a defaultValue. Meaning the property will always have a value, as a default value was supplied. Though as `name` is defined as optional, you always need to properly unwrap the optional.

Thus something like
```swift
@Parameter(.necessity(.optional))
var name: String = "Test"
```
might be useful.

**Comment by theMomax** [comment]
I would argue `@Parameter var name: String? = "Test"` to be valid. For the exporter anything that has a default value is optional. However, there is another aspect that **is** important to the exporter:

```swift
// can be overridden to be nil
@Parameter var name: String? = "Test"
// cannot be overridden to be nil
@Parameter var name: String = "Test"
```

The exporter thus needs to know if an optional (i.e. not required) parameter is an `Optional` (as in can be set to null/nil explicitly) or not. It needs to be able to express this when it provides the value for the `@Parameter`.

**Comment by PSchmiedmayer** [comment]
@theMomax That's a good question and thanks for raising it as a GitHub issue!
I like the natural approach detailed as (A) above and would agree with the [comment above](https://github.com/Apodini/Apodini/issues/80#issuecomment-751294746) that it might still be necessary to have an optional type for a `Parameter` that has a default value. As @theMomax stated the request could manually carry a `nil`/`null` value that would be able to override the default value in `@Parameter var name: String? = "Test"`.

**Comment by theMomax** [comment]
Thanks for all the feedback!

To sum up: We do not want to provide explicit options on `@Parameter` for controlling its necessity. Instead we derive two characteristics from the variable's declaration:

### Optionality

Is **true** if the initial request is valid even if no value was provided for this variable.

* Is **true** if either:
     * the `Parameter`'s `Element` is `ExpressibleByNilLiteral`
     * the `Parameter`'s `defaultValue` is not `nil`
* Is **false** otherwise

### Nullability

Is **true** if a request which contains a `null` value for this variable is valid.

* Is **true** if:
     * the `Parameter`'s `Element` is `ExpressibleByNilLiteral`
* Is **false** otherwise

**Comment by bauer-andreas** [comment]
Ref: This way of handling was incorporated into #81.
