### ISSUE TITLE
Unwrap EventLoopFutures between response transformer steps

### ISSUE THREAD

**Issue by bauer-andreas** [Apodini/Apodini#97]
Related: #94 
CC: @tgymnich (as you are working on the new `Encodable` replacement), @moritzschuell, @theMomax, @PSchmiedmayer, @nerdsupremacist 

As of now the Input type of `ResponseTransformers` must always match the Output type of the modified `Handler`.
E.g. having a handler with `func handle() -> String`, your transformed needs to be defined as `func transform(response: String) -> Output`.
There is one exception to this rule: `Action`s. For a `Handler` returning e.g. `Action<String>` you can defined a `ResponseTransformer` transforming the wrapped `String` value.

An additional edge case worth to be considered is a `Handler` returning `EventLoopFuture<...>`. Currently a ResponseTransformer must be defined to have an input type of `EventLoopFuture` if the `Handler` returns `EventLoopFuture`. I think it would be a great addition to the API if we support unwrapping `EventLoopFutures` between response transformer steps.
Below I supplied a list highlighting possible response transformer signatures for a given handle signature. 

* `func handle() -> String`
  * `func transform(response: String) -> Output`
* `func handle() -> Action<String>`
  * `func transform(response: String) -> Output`
  * `func transform(response: Action<String>) -> Output`
    This case is currently possible, to define (meaning no compile time error), but the current `RequestHandler` will currently always unwrap the Action, and will only call transformers for `.final` and `.send` (when a value is supplied).
  I think it would be a valid discussion if a response transformer should be allowed to transform the return action from a `Handler`. I would assume that it may be a problem when a `Handler` thinks it closed a server side stream with `.end`, but a `ResponseTransformer` modifies that. Otherwise I could also see benefits on allowing this.
* ~`func handle() -> Action<Action<String>>`~ **wrapping Actions is disallowed**
* `func handle() -> EvenLoopFuture<String>`
  * `func transform(response: String) -> Output`
  * `func transform(response: EventLoopFuture<String>) -> Output`
    I think allowing this is perfectly fine and just improves compatibility of possible building blocks.
* `func handle() -> Action<EventLoopFuture<String>>`
  * `func transform(response: String) -> Output`
  * `func transform(response: EventLoopFuture<String>) -> Output`
  * `func transform(response: Action<EventLoopFuture<String>>) -> Output`
    Depending on the discussion above, this case might be allowed.
* `func handle() -> EventLoopFuture<EventLoopFuture<String>>`
  While not particularly useful or considered good practice, such definitions/types are still possible. In an ideal world, unwrapping such nested futures would be possible. But supporting any number of nested `EventLoopFuture`s is probably not feasible.
  * `func transform(response: String) -> Output`
  * `func transform(response: EventLoopFuture<String>) -> Output`
  * `func tranform(response: EventLoopFuture<EventLoopFuture<String>>) -> Output`

To throw in some additional complications:  Optionals.
A `Handler` may return any optional type (even any amount of nested optionals).

I think there are two things to consider her:
* How do response transformer treat optionals
* How do InterfaceExporters treat optionals

Considering a Handler returning `String?`:
* `func handle() -> Optional<String>`
  * `func transform(response: String?) -> Output`
   Is always executed
  * `func transform(response: String) -> Output`
  Is only executed if the optional can be unwrapped (similar to how we currently do not call the transformers for actions `.end` and `.nothing`, and transformers are called on the wrapped value for `.send` and `.final`)

In regards to InterfaceExporters I think a valid approach would be to map an empty Optional to `Action.nothing`. For reference, any return value of a `Handler` not specifically returning `Action`, we wrap the value into `Action.final` and pass it to the exporter.

**Comment by PSchmiedmayer** [comment]
@Supereg Thanks for documenting the issue! I agree that the current approach of `ResponseTransformer`s simply matching the output type of the previous `ResponseTransformer` or `Handler` is not idea. This is especially visible in the `EventLoopFuture` cases. As described in my review of #94 I would suggest to reconsider the order of `EventLoopFuture`s and `Action`s/`Encodable` types and I will try to experiment a bit with this. In addition I would suggest the following approach to `ResponseTransformer`s:
1. `ResponseTransformer` always gets passed in an `Action` that is generic over the type of the response of the previous `Handler` or `ResponseTransformer`. If the `Handler` or `ResponseTransformer` returned an `Action` it is the exact same type, if it is only an type confirming to `Encodable` and not an `Action` (and considering that we have unwrapped all `EventLoopFutures` if they can only appear on the outer layer) the default mapping strategy described below and in your issue is applied: An `finish(...)` is passed to the `ResponseTransformer`.
2. A `EncodableResponseTransformer` or similar is able to map `Encodable` types without having to worry about the `Action` type. E.g. it only maps in the `.send` and `.finish` cases. If the previous `Handler` or `ResponseTransformer` returned an `Action.end` or `Action.nothing` it is not called and will not map anything.
3. I would suggest that `Optional`s are always passed on the `ResponseTransformer`s/`EncodableResponseTransformer`s and can allow a to e.g. replace a `nil` value with some replacement value that conforms to encodable or choose a different strategy. But there is a problem: Returning a `nil` in a `Handler` with an optional `Response` type can either be be mapped to a `.finish(nil)` or a `.nothing` when passing it down the chain. Mapping it to `.finish(nil)` would close e.g. a service side stream. Alternatively it could be mapped to a `.nothing` but this would make it impossible to explicitly pass a `.finish(nil)` down the chain as it would be mapped to a `.nothing` and would not reach the outer layer of `ResponseTransformers`.

Regarding the problem raised in 3.:  I think it might be desirable to create an additional `Action` case like `.automatic` or similar that would only be mapped at the very end and would be chosen if e.g. a `Handler` only returns a `Encodable` type that is not an `Action`. The `ResponseTransformer` would be able to transform the result and the `InterfaceExporter` would eventually be able to map the `automatic` case to a `nothing` and a `.finish(nil)` would have its desired effect of closing the channel.

Regarding the Interface Exporters: I think the approach described in the issue makes sense to me.
- Optionals from a `Handler` or a `ResponseTransformer` are mapped to `.nothing` after the `Handler` and all `ResponseTransformers` have been passed and the value is indeed `.none` at the end of the chain
- Any `Encodable` values that are not `Actions` are mapped to a `.final` call. The developer must explicitly specify a `.send` if the developer wants to keep the channel open after returning the response

**Comment by PSchmiedmayer** [comment]
@Supereg @moritzschuell, @theMomax, @nerdsupremacist I have experimented a bit after reviewing #94 and adding my comment here and created a draft PR (#98) to compare the diff and discuss the approach. As far as I can see this would solve the issues raised in the review of #94 and this issue. It would be great to hear your opinion on what you think and if and what we should merge the ideas into develop.

**Comment by theMomax** [comment]
Just so it is also documented here: @PSchmiedmayer described a problem [here](https://github.com/Apodini/Apodini/pull/94#discussion_r551177038):
The basic problem is that `Action<EventLoopFuture<String>>` does limit what is expressible in a `Handler`: e.g. one cannot base the decision whether the `Action` should be `.nothing` or `.final()` based on a database query without blocking the eventloop.

Thus we always have to accept `EventLoopFuture` as the outermost type.

Examples:
1. `String` ✅
2. `EventLoopFuture<String>` ✅
3. `EventLoopFuture<Optional<String>>` ✅
4. `Optional<EventLoopFuture<String>>` ❓
    a) exported type is  `String`; `nil` means `Action.nothing`
    b) exported type is `Optional<String>`; `nil` means `Action.final(nil)`
5. `EventLoopFuture<Action<String>>` ✅
6. `Action<EventLoopFuture<String>>` ❓
7. `EventLoopFuture<EventLoopFuture<Action<String>>` ❓
8. `Optional<Optional<String>>` ❓
    a) exported type is  `Optional<String>`; `nil` means `Action.nothing`; `.some(nil)` means `Action.final(nil)`
    b) exported type is `Optional<Optional<String>>`; `nil` means `Action.final(nil)`; `.some(nil)` means `Action.final(.some(.nil))`
        (Can this even be expressed for all exporters? (JSON: both, `nil` and `.some(nil)` are encoded to `null`)

I think we all agree that those examples marked with ✅ must be supported by Apodini. What remains to be decided is whether we want to support any of the examples marked with ❓and, in case we do, what they would mean.

**Comment by PSchmiedmayer** [comment]
@theMomax Great summary!
I agree with all the ✅👍

Regarding the ❓
4. If we want to support this I would prefer option a) out of the two proposed actions. In general I would vote agains supporting this but compared to 6 I could see some use cases that would use this but would considers this more or less an anti pattern when using EventLoopFutures and would try to discourage the developer to return `Optional<EventLoopFuture<...>>`. ❌
6. I would vote against supporting anything that doesn't conform to `Encodable` (or something smarter that would replace `Encodable` as proposed by @nerdsupremacist) within an `Action` to ensure that all `Actions` can be easily passed down to interface exporters or response transformers without any side effects after passing it to the next element/exporter. ❌
7. I would consider this possible and supportable by the current implementation. Even though it might not look pretty and doesn't really reflect best practices it is something we can easily support and allow if the developer needs to return such a nested future. ✅
8. I would be fine with supporting 8 a). Similar to 7 I would consider it a task of the developer to unwrap nested optionals down to a level that is expressible by `Optional<String>`. I would consider nested optionals an anti pattern that would create a lot of ambiguities for the exporters and how the differences are expressed in the encoding styles if we would choose b). Out of the options listed here I would consider a) the more reasonable and a solution we could support quite easily support. ✅

I think supporting 4, 7, or 8 somehow comes down how forgiving we want to be with developer errors. As working with futures is already hard and challenging for newcomers I could see how supporting these use cases would benefit a beginner developer getting used to `Optionals` and `EventLoopFutures`.

**Comment by theMomax** [comment]
I agree that nested `EventLoopFuture` (7) is reasonable as getting this right as a beginner can cause some struggle. I would vote against 4a) and 8a) because I dislike the idea of mixing up `Action` with `Optional`. Those are separate types with different meaning and having a hidden mapping from `Optional` to `Action` could be a caveat when trying to understand a web service.

**Comment by PSchmiedmayer** [comment]
@theMomax I could agree with only accepting 7 from the ❓ choice.
I would suggest to add the topic to the meeting agenda of the next meeting and discuss it there with the whole @Apodini/apodini team. As all the elements mentioned above should be implementable with a reasonable effort or removed with a reasonable effort and 1, 2, 3, 5 & 7 are implemented in #98 I think it would be acceptable to move forward with considering what elements of #98 and #94 we want to integrate in develop.

**Comment by nerdsupremacist** [comment]
I played around with a new ResponseType protocol that would require very little implementation from user's and would allow us to make event loop futures and actions work by decoupling the Type from the Encodable type that results from it:

```

public indirect enum ResponseOfType<T : Encodable> {
    case future(EventLoopFuture<ResponseOfType<T>>)
    case value(T)
    case array([ResponseOfType<T>])
    case optional(ResponseOfType<T>?)
    case action(Action<ResponseOfType<>>)
}

public protocol ResponseType {
    associatedtype EncodableType: Encodable
    func response() -> ResponseOfType<Self.EncodableType>
}

extension Action: ResponseType where Value: ResponseType {
    public typealias EncodableType = Value.EncodableType

    public func response() -> ResponseOfType<Value.EncodableType> {
        return .action(map { $0.response() })
    }
}

extension ResponseType where Self: Encodable {
    public typealias EncodableType = Self

    public func response() -> ResponseOfType<Self> {
        return .value(self)
    }
}

extension Array: ResponseType where Element: ResponseType {
    public typealias EncodableType = [Element.EncodableType]

    public func response() -> ResponseOfType<[Element.EncodableType]> {
        return .array(map { $0.response() })
    }
}

extension Optional: ResponseType where Wrapped: ResponseType {
    public typealias EncodableType = Wrapped.EncodableType?

    public func response() -> ResponseOfType<Wrapped.EncodableType?> {
        return .optional($0?.response())
    }
}
```

**Comment by PSchmiedmayer** [comment]
@Supereg @theMomax Based on the current state of develop after #98 and the discussion in the last team meeting I am closing this issue.
As we don't allow `Optional<Response<Encodable>>` in the current implementation the need for an [`.automatic` Response case as mentioned above](https://github.com/Apodini/Apodini/issues/97#issuecomment-753856185) would also be obsolete.
